# Dependabot configuration file.
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
version: 2

enable-beta-ecosystems: true

updates:
  - package-ecosystem: "pub"
    directory: "."
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "example/midi_player_example"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "packages/midi_player"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
