name: midi_player_example
description: Midi player example.
version: 0.2.0
environment:
  sdk: ^3.9.0
publish_to: none
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ">=1.0.8"
  tekartik_midi:
    git:
      url: https://github.com/tekartik/midi.dart
    version: '>=0.1.0'
  tekartik_midi_player:
    git:
      url: https://github.com/tekartikprj/midi_player
      path: packages/midi_player
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
  path_provider: ">=2.1.5"
  path: ">=1.9.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  tekartik_test_menu_flutter:
    git:
      url: https://github.com/tekartik/test_menu_flutter
      path: test_menu_flutter
    version: '>=0.2.0'
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      path: packages/lints_flutter
    version: '>=0.1.0'

#dependency_overrides:
#  tekartik_test_menu_flutter:
#    path: ../../../../../github.com/tekartik/test_menu_flutter/test_menu_flutter
#  tekartik_test_menu:
#    path: ../../../../../github.com/tekartik/test_menu.dart/test_menu

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/pop.mid
resolution: workspace
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
